kafka.bootstrap.servers=PLAINTEXT://kafka.cm3202.uk:9092
mp.messaging.incoming.incident-request-in.connector=smallrye-kafka
mp.messaging.incoming.incident-request-in.topic=incident-request
mp.messaging.incoming.incident-request-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.incident-request-in.group.id=my-group
mp.messaging.outgoing.patient-update.connector=smallrye-kafka
mp.messaging.outgoing.patient-update.topic=patient-update
mp.messaging.outgoing.patient-update.value.serializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
mp.messaging.outgoing.patient-update.specific.protobuf.value.type=com.emergingtech.proto.Patient$PatientUpdate
mp.messaging.outgoing.patient-update.protobuf.value.message=com.emergingtech.proto.Patient$PatientUpdate
mp.messaging.outgoing.patient-update.schema.registry.url=http://localhost:8081