kafka.bootstrap.servers=PLAINTEXT://localhost:9092
mp.messaging.incoming.incident-request-in.connector=smallrye-kafka
mp.messaging.incoming.incident-request-in.topic=incident-request
mp.messaging.incoming.incident-request-in.value.deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
mp.messaging.incoming.incident-request-in.specific.protobuf.value.type=com.emergingtech.proto.Incident$IncidentRequest
mp.messaging.incoming.incident-request-in.schema.registry.url=http://localhost:8081
mp.messaging.incoming.incident-request-in.protobuf.value.message=com.emergingtech.proto.Incident$IncidentRequest
mp.messaging.incoming.incident-request-in.group.id=my-group
mp.messaging.outgoing.incident-request-out.connector=smallrye-kafka
mp.messaging.outgoing.incident-request-out.topic=incident-request
mp.messaging.outgoing.incident-request-out.value.serializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
mp.messaging.outgoing.incident-request-out.specific.protobuf.value.type=com.emergingtech.proto.Incident$IncidentRequest
mp.messaging.outgoing.incident-request-out.protobuf.value.message=com.emergingtech.proto.Incident$IncidentRequest
mp.messaging.outgoing.incident-request-out.schema.registry.url=http://localhost:8081