mp.messaging.incoming.action-request.connector=smallrye-kafka
mp.messaging.incoming.action-request.topic=action-request
mp.messaging.incoming.action-request.value.deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
mp.messaging.incoming.action-request.specific.protobuf.value.type=com.emergingtech.proto.ResourceMapper$PractitionerActionRequest
mp.messaging.incoming.action-request.schema.registry.url=http://localhost:8081