mp.messaging.incoming.action-request.connector=smallrye-kafka
mp.messaging.incoming.action-request.topic=action-request
mp.messaging.incoming.action-request.value.deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
mp.messaging.incoming.action-request.specific.protobuf.value.type=com.emergingtech.proto.ResourceMapper$PractitionerActionRequest
mp.messaging.incoming.action-request.schema.registry.url=http://localhost:8081
mp.messaging.incoming.action-request.bootstrap.servers=localhost:9092
mp.messaging.incoming.mapping-response.connector=smallrye-kafka
mp.messaging.incoming.mapping-response.topic=mapping-response
mp.messaging.incoming.mapping-response.value.deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
mp.messaging.incoming.mapping-response.specific.protobuf.value.type=com.emergingtech.proto.ResourceMapper$ResourceMappingResponse
mp.messaging.incoming.mapping-response.schema.registry.url=http://localhost:8081
mp.messaging.incoming.mapping-response.bootstrap.servers=localhost:9092
mp.messaging.outgoing.mapping-request.connector=smallrye-kafka
mp.messaging.outgoing.mapping-request.topic=mapping-request
mp.messaging.outgoing.mapping-request.value.serializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
mp.messaging.outgoing.mapping-request.specific.protobuf.value.type=com.emergingtech.proto.ResourceMapper$ResourceMappingRequest
mp.messaging.outgoing.mapping-request.protobuf.value.message=com.emergingtech.proto.ResourceMapper$ResourceMappingRequest
mp.messaging.outgoing.mapping-request.schema.registry.url=http://localhost:8081
quarkus.http.port=8200