
mp.messaging.incoming.resource-request.connector=smallrye-kafka
mp.messaging.incoming.resource-request.topic=resource-request
mp.messaging.incoming.resource-request.value.deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
mp.messaging.incoming.resource-request.specific.protobuf.value.type=com.emergingtech.proto.ResourceMapper$ResourceMappingRequest
mp.messaging.incoming.resource-request.schema.registry.url=http://localhost:8081