# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x16\x63om.emergingtech.proto\"1\n\x0b\x43oordinates\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x0c\n\x04srid\x18\x03 \x01(\x05*Q\n\x0eIncidentStatus\x12 \n\x1c\x41WAITING_PRACTITIONER_ACTION\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\x0c\n\x08RESOLVED\x10\x02*G\n\x12PractitionerAction\x12\x13\n\x0fNO_ACTION_TAKEN\x10\x00\x12\x1c\n\x18HOSPITAL_TRANSFER_URGENT\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INCIDENTSTATUS']._serialized_start=91
  _globals['_INCIDENTSTATUS']._serialized_end=172
  _globals['_PRACTITIONERACTION']._serialized_start=174
  _globals['_PRACTITIONERACTION']._serialized_end=245
  _globals['_COORDINATES']._serialized_start=40
  _globals['_COORDINATES']._serialized_end=89
# @@protoc_insertion_point(module_scope)
