quarkus.index-dependency.com-emergingtech-orchestration-db-mgmt.group-id=com.emergingtech.orchestration
mp.messaging.outgoing.action-request.connector=smallrye-kafka
mp.messaging.outgoing.action-request.topic=action-request
mp.messaging.outgoing.action-request.value.serializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
mp.messaging.outgoing.action-request.specific.protobuf.value.type=com.emergingtech.proto.ResourceMapper$PractitionerActionRequest
mp.messaging.outgoing.action-request.schema.registry.url=http://localhost:8081
kafka.bootstrap.servers=kafka.cm3202.uk