quarkus.index-dependency.com-emergingtech-orchestration-db-mgmt.group-id=com.emergingtech.orchestration
mp.messaging.outgoing.action-request.connector=smallrye-kafka
mp.messaging.outgoing.action-request.topic=action-request
mp.messaging.outgoing.action-request.value.serializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
mp.messaging.outgoing.action-request.specific.protobuf.value.type=com.emergingtech.proto.ResourceMapper$PractitionerActionRequest
mp.messaging.outgoing.action-request.schema.registry.url=http://localhost:8081
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type
quarkus.http.port=8100
kafka.bootstrap.servers=PLAINTEXT://kafka.cm3202.uk:9092