quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changeLog.sql
quarkus.datasource.devservices.enabled=false
